services:
  whatsapp_app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: whatsapp_app
    restart: unless-stopped
    ports:
      - 9002:9000
    volumes:
      - ./:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php_conf.ini
    networks:
      - whatsapp_network

   #Nginx Service
  whatsapp_webserver:
    image: nginx:alpine
    container_name: whatsapp_webserver
    restart: unless-stopped
    ports:
      - 8002:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - whatsapp_network

networks:
  whatsapp_network:
    name: whatsapp_network
    driver: bridge
