version: '3.2'

services:
  whatsapp_app:
    build:
      context: ./docker
      dockerfile: Dockerfile
    working_dir: /var/www/
    container_name: whatsapp_app
    ports:
      - 9002:9000
    volumes:
      - ./:/var/www/
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php_conf.ini
    networks:
      - whatsapp_network

   #Nginx Service
  whatsapp_webserver:
    image: nginx:alpine
    container_name: whatsapp_webserver
    restart: unless-stopped
    ports:
      - 8001:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - whatsapp_network

  whatsapp_mysql:
    image: 'mysql:latest'
    container_name: whatsapp_mysql
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'tabela'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_OPTIONS: "--sort-buffer-size=1024M"  # Ajuste conforme necessário
    volumes:
      - './.docker/mysql:/var/lib/mysql'
      - ./docker/mysql/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf
    networks:
      - whatsapp_network

networks:
  whatsapp_network:
    name: whatsapp_network
    driver: bridge
